name: ✨ Feature Request
description: Suggest a new feature or enhancement for Sparky AI Browser
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees:
  - jishnusygal

body:
  - type: markdown
    attributes:
      value: |
        ## 🐕 Thanks for suggesting a feature for Sparky AI Browser!
        
        We appreciate your interest in making Sparky even better. Please fill out the sections below to help us understand your feature request.

  - type: checkboxes
    id: existing-check
    attributes:
      label: 🔍 Is this feature request related to an existing issue?
      description: Please search existing issues to avoid duplicates
      options:
        - label: I have searched existing issues and this feature hasn't been requested
          required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: 📋 Feature Category
      description: What category does this feature belong to?
      options:
        - "🧠 AI/Intelligence - Core AI functionality"
        - "🎨 UI/UX - User interface improvements"
        - "🔐 Authentication - Login and security features"
        - "📱 Browser Integration - Chrome extension features"
        - "⚡ Performance - Speed and optimization"
        - "🔧 Developer Tools - Development experience"
        - "📚 Documentation - Guides and help content"
        - "🛡️ Security - Privacy and security features"
        - "🌐 Compatibility - Browser/platform support"
        - "🔗 Integrations - Third-party service connections"
        - "📊 Analytics - Usage tracking and insights"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Priority Level
      description: How important is this feature to you?
      options:
        - "🔥 Critical - Blocking my usage"
        - "⚡ High - Would significantly improve my workflow"
        - "📝 Medium - Nice to have"
        - "💡 Low - Small improvement"
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: 🚫 Problem Description
      description: What problem does this feature solve? What's frustrating about the current experience?
      placeholder: "I'm frustrated when..."
      value: |
        **Current Situation:**
        
        
        **Pain Points:**
        
        
        **Impact:**
        
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "I would like Sparky to..."
      value: |
        **Feature Description:**
        
        
        **How it should work:**
        1. 
        2. 
        3. 
        
        **Expected behavior:**
        
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: 📖 User Stories
      description: Describe how different users would interact with this feature
      placeholder: "As a [type of user], I want [goal] so that [benefit]"
      value: |
        **User Story 1:**
        As a [user type], I want [feature] so that [benefit].
        
        **User Story 2:**
        As a [user type], I want [feature] so that [benefit].
        
        **Acceptance Criteria:**
        - [ ] 
        - [ ] 
        - [ ] 

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "Alternative approaches could be..."

  - type: textarea
    id: technical-details
    attributes:
      label: 🔧 Technical Considerations
      description: Any technical details, constraints, or implementation ideas?
      placeholder: "This might require..."
      value: |
        **Technical Requirements:**
        
        
        **Potential Challenges:**
        
        
        **Dependencies:**
        

  - type: textarea
    id: mockups-examples
    attributes:
      label: 🎨 Mockups/Examples
      description: Add any sketches, mockups, or examples that illustrate your idea
      placeholder: "Attach images, links to examples, or describe the visual design"

  - type: dropdown
    id: complexity
    attributes:
      label: 📊 Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "🟢 Simple - Small change or addition"
        - "🟡 Medium - Moderate development effort"
        - "🟠 Complex - Significant development effort"
        - "🔴 Very Complex - Major architectural changes"
        - "❓ Unknown - Not sure about complexity"

  - type: checkboxes
    id: user-types
    attributes:
      label: 👥 Target Users
      description: Who would benefit from this feature?
      options:
        - label: New users just getting started with Sparky
        - label: Regular users who use Sparky daily
        - label: Power users who need advanced features
        - label: Developers integrating with Sparky
        - label: Enterprise users with specific needs

  - type: textarea
    id: success-metrics
    attributes:
      label: 📈 Success Metrics
      description: How would we measure the success of this feature?
      placeholder: "We'd know this feature is successful when..."
      value: |
        **Metrics to track:**
        - 
        - 
        
        **Success criteria:**
        - 
        - 

  - type: checkboxes
    id: contribution
    attributes:
      label: 🤝 Contribution
      description: Would you be interested in helping implement this feature?
      options:
        - label: I'd like to work on implementing this feature
        - label: I can help with testing and feedback
        - label: I can provide design input or mockups
        - label: I can help with documentation
        - label: I prefer to just provide the idea

  - type: textarea
    id: additional-context
    attributes:
      label: 📚 Additional Context
      description: Add any other context, screenshots, or information about the feature request
      placeholder: "Additional details..."

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 🚀 What happens next?
        
        1. **Triage**: We'll review your feature request and add appropriate labels
        2. **Discussion**: The community and maintainers will discuss the proposal
        3. **Prioritization**: We'll determine when this might be implemented
        4. **Implementation**: Development begins (either by maintainers or contributors)
        5. **Testing**: Feature testing and refinement
        6. **Release**: Feature ships in a new version of Sparky
        
        **Thank you for helping make Sparky better! 🐕**